# Generated by Django 5.0.2 on 2024-03-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='flat_no',
        ),
    ]
