# Generated by Django 5.0.2 on 2024-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_wallet_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallet",
            name="amount",
            field=models.DecimalField(decimal_places=1, max_digits=30, null=True),
        ),
    ]
