# Generated by Django 5.0.2 on 2024-03-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraddress_status_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='landmark',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
