# Generated by Django 5.0.2 on 2024-04-24 17:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_wallettransaction_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
