# Generated by Django 5.0.2 on 2024-04-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_alter_wallettransaction_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettransaction",
            name="is_credit",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
