# Generated by Django 5.0.2 on 2024-04-08 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupon", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coupon",
            name="is_available",
        ),
    ]
