# Generated by Django 4.2.5 on 2024-02-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
