# Generated by Django 5.0.2 on 2024-04-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brand", "0001_initial"),
        ("product", "0002_alter_product_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="brand.brand"
            ),
            preserve_default=False,
        ),
    ]
