# Generated by Django 4.2.5 on 2024-04-27 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_brand"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="p_price",
        ),
    ]
