# Generated by Django 5.0.2 on 2024-04-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("discount", models.IntegerField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
