# Generated by Django 4.2.5 on 2024-02-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
