# Generated by Django 5.0.2 on 2024-04-17 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="offer",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="offer",
            name="start_date",
        ),
        migrations.AddField(
            model_name="offer",
            name="active_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="offer",
            name="expiry_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
