# Generated by Django 4.2.5 on 2024-02-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_offer_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offer_percentage',
            new_name='discount',
        ),
    ]
