# Generated by Django 5.0.2 on 2024-03-22 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="full_name",
            new_name="name",
        ),
    ]
