# Generated by Django 5.0.2 on 2024-04-06 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveyAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.BigIntegerField()),
                ("country", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("landmark", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="orders",
            name="total",
        ),
        migrations.AddField(
            model_name="orders",
            name="discount_amt",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(default="Cash On Delivery", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="product_price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="sub_total",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cart.deliveyaddress"
            ),
        ),
    ]
