# Generated by Django 5.0.2 on 2024-04-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_deliveyaddress_remove_orders_total_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(default="Pending", max_length=100),
        ),
    ]
