# Generated by Django 5.0.2 on 2024-03-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitems",
            name="total",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
