# Generated by Django 5.0.2 on 2024-04-06 06:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0003_alter_orders_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="payment_method",
        ),
    ]
