# Generated by Django 5.0.2 on 2024-04-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_remove_orders_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="discount_amt",
            field=models.IntegerField(default=0),
        ),
    ]
