# Generated by Django 5.0.2 on 2024-04-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0005_alter_orders_discount_amt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitems",
            name="total",
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
        migrations.AlterField(
            model_name="orders",
            name="discount_amt",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="orders",
            name="product_price",
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
        migrations.AlterField(
            model_name="orders",
            name="sub_total",
            field=models.DecimalField(decimal_places=1, max_digits=30),
        ),
    ]
