# Generated by Django 5.0.2 on 2024-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_alter_cartitems_total_alter_orders_discount_amt_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
