# Generated by Django 5.0.2 on 2024-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0008_orders_product_qty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(default="Cash On Delivery", max_length=100),
            preserve_default=False,
        ),
    ]
