# Generated by Django 4.2.5 on 2024-04-27 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0009_alter_orders_payment_method"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitems",
            name="total",
        ),
    ]
