# Generated by Django 4.2.5 on 2024-04-29 18:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0010_remove_cartitems_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="sub_total",
        ),
    ]
