# Generated by Django 4.2.5 on 2024-05-01 12:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0012_orders_razorpay_order_id_orders_razorpay_payment_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="razorpay_signature",
        ),
    ]
