# Generated by Django 4.2.5 on 2024-05-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0013_remove_orders_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="return_status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
