# Generated by Django 4.2.5 on 2024-05-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_orders_return_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='return_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
