# Generated by Django 4.2.5 on 2024-05-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0016_alter_orders_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cart.deliveyaddress"
            ),
        ),
    ]
